module.exports = {
   // TEMPLATE
   // {
   //    name: '',
   //    skin: '',
   //    rarity: '',
   //    min_float:0,
   //    max_float:,
   // },

   FractureCase: [

      {
         name: 'Negev',
         skin: 'Ultralight',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.79,

      },

      {
         name: 'SG 553',
         skin: "Ol' Rusty",
         rarity: 'blue',
         min_float: 0,
         max_float: 0.7,

      },
      {
         name: 'P2000',
         skin: 'Gnarled',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,

      },
      {
         name: 'P90',
         skin: 'Freight',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,

      },
      {
         name: 'PP-Bizon',
         skin: 'Runic',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,

      },
      {
         name: 'P250',
         skin: 'Cassette',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.6,

      },
      {
         name: 'SSG 08',
         skin: 'Mainframe 001',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,

      },
      {
         name: 'Galil AR',
         skin: 'Connexion',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.8,

      },
      {
         name: 'MP5-SD',
         skin: 'Kitbash',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.8,

      },
      {
         name: 'Tec-9',
         skin: 'Brother',
         rarity: 'purple',
         min_float: 0,
         max_float: 1,

      },
      {
         name: 'MAC-10',
         skin: 'Allure',
         rarity: 'purple',
         min_float: 0,
         max_float: 1,

      },
      {
         name: 'MAG-7',
         skin: 'Monster Call',
         rarity: 'purple',
         min_float: 0,
         max_float: 1,

      },
      {
         name: 'XM1014',
         skin: 'Entombed',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.5,

      },
      {
         name: 'Glock-18',
         skin: 'Vogue',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.75,

      },
      {
         name: 'M4A4',
         skin: 'Tooth Fairy',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.73,

      },
      {
         name: 'AK-47',
         skin: 'Legion of Anubis',
         rarity: 'red',
         min_float: 0,
         max_float: 0.7,

      },
      {
         name: 'Desert Eagle',
         skin: 'Printstream',
         rarity: 'red',
         min_float: 0,
         max_float: 0.8,

      },


   ],
   PrismaCase: [
      {
         name: 'MP7',
         skin: 'Mischief',
         rarity: 'blue',
         min_float: 0.1,
         max_float: 1,
      },

      {
         name: 'P90',
         skin: 'Off World',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.75,
      },

      {
         name: 'MAC-10',
         skin: 'Whitefish',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,
      },

      {
         name: 'Galil AR',
         skin: 'Akoben',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.75,
      },

      {
         name: 'P250',
         skin: 'Verdigris',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.7,
      },

      {
         name: 'FAMAS',
         skin: 'Crypsis',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.55,
      },

      {
         name: 'AK-47',
         skin: 'Uncharted',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.75,
      },

      {
         name: 'MP5-SD',
         skin: 'Gauss',
         rarity: 'purple',
         min_float: 0,
         max_float: 1,
      },

      {
         name: 'Tec-9',
         skin: 'Bamboozle',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.8,
      },

      {
         name: 'UMP-45',
         skin: 'Moonrise',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.4,
      },
      {
         name: 'Desert Eagle',
         skin: 'Light Rail',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.9,
      },
      {
         name: 'AWP',
         skin: 'Atheris',
         rarity: 'purple',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'R8 Revolver',
         skin: 'Skull Crusher',
         rarity: 'pink',
         min_float: 0.25,
         max_float: 0.8,
      },
      {
         name: 'XM1014',
         skin: 'Incinegator',
         rarity: 'pink',
         min_float: 0.14,
         max_float: 0.65,
      },
      {
         name: 'AUG',
         skin: 'Momentum',
         rarity: 'pink',
         min_float: 0.05,
         max_float: 1,
      },
      {
         name: 'Five-SeveN',
         skin: 'Angry Mob',
         rarity: 'red',
         min_float: 0,
         max_float: 0.7,
      },
      {
         name: 'M4A4',
         skin: 'The Emperor',
         rarity: 'red',
         min_float: 0,
         max_float: 0.8,
      },


   ],
   Dust2: [

      {
         name: 'Nova',
         skin: 'Predator',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'SCAR-20',
         skin: 'Sand Mesh',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'P90',
         skin: 'Sand Spray',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'MP9',
         skin: 'Sand Dashed',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'P250',
         skin: 'Sand Dune',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'G3SG1',
         skin: 'Desert Storm',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'Tec-9',
         skin: 'VariCamo',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.6,
      },
      {
         name: 'Sawed-Off',
         skin: 'Snake Camo',
         rarity: 'light_blue',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'MAC-10',
         skin: 'Palm',
         rarity: 'light_blue',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'Five-SeveN',
         skin: 'Orange Peel',
         rarity: 'light_blue',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'AK-47',
         skin: 'Safari Mesh',
         rarity: 'light_blue',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'PP-Bizon',
         skin: 'Brass',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'M4A1-S',
         skin: 'VariCamo',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.6,
      },
      {
         name: 'SG 553',
         skin: 'Damascus Steel',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'P2000',
         skin: 'Amber Fade',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.4,
      },
      {
         name: 'R8 Revolver',
         skin: 'Amber Fade',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.4,
      },




   ],

   Inferno: [
      {
         name: 'Te-9',
         skin: 'Brass',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'Dual Berettas',
         skin: 'Anodized Navy',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.08,
      },
      {
         name: 'M4A4',
         skin: 'Tornado',
         rarity: 'light_blue',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'P250',
         skin: 'Gunsmoke',
         rarity: 'light_blue',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'Nova',
         skin: 'Walnut',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'MAG-7',
         skin: 'Sand Dune',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      }
   ],
   Inferno2018: [

      {
         name: 'SG 553',
         skin: 'Integrale',
         rarity: 'pink',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'Dual Berettas',
         skin: 'Twin Turbo',
         rarity: 'pink',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'AK-47',
         skin: 'Safety Net',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.6,
      },
      {
         name: 'MP7',
         skin: 'Fade',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.25,
      },
      {
         name: 'P250',
         skin: 'Vino Primo',
         rarity: 'purple',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'USP-S',
         skin: 'Check Engine',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.6,
      },
      {
         name: 'SSG 08',
         skin: 'Hand Brake',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'M4A4',
         skin: 'Converter',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.4,
      },
      {
         name: 'Sawed-Off',
         skin: 'Brake Light',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.08,
      },
      {
         name: 'Glock-18',
         skin: 'High Beam',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.08,
      },
      {
         name: 'MAC-10',
         skin: 'Calf Skin',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'R8 Revelover',
         skin: 'Nitro',
         rarity: 'light_blue',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'PP-Bizon',
         skin: 'Candy Apple',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.3,
      },
      {
         name: 'MP9',
         skin: 'Slide',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'MP5-SD',
         skin: 'Dirt Drop',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'AUG',
         skin: 'Sweeper',
         rarity: 'grey',
         min_float: 0,
         max_float: 0.6,
      },
      {
         name: 'UMP-45',
         skin: 'Mudder',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'MAG-7',
         skin: 'Rust Coat',
         rarity: 'grey',
         min_float: 0,
         max_float: 1,
      }
   ],
   Nuke2018: [
      {
         name: 'M4A1-S',
         skin: 'Control Panel',
         rarity: 'pink',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'Tec-9',
         skin: 'Remote control',
         rarity: 'pink',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'Glock-18',
         skin: 'Nuclear Garden',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.7,
      },
      {
         name: 'MAG-7',
         skin: 'Core Breach',
         rarity: 'pink',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'AUG',
         skin: 'Random Access',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'AWP',
         skin: 'Acheron',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.83,
      },
      {
         name: 'MP5-SD',
         skin: 'Co-Processor',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'P90',
         skin: 'Facility Negative',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'P250',
         skin: 'Exchanger',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'Galil AR',
         skin: 'Cold Fusion',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.83,
      },
      {
         name: 'M4A4',
         skin: 'Mainframe',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'Negev',
         skin: 'Bulkhead',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'MP7',
         skin: 'Motherboard',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'PP-Bizon',
         skin: 'Facility Sketch',
         rarity: 'grey',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'Five-SeveN',
         skin: 'Coolant',
         rarity: 'grey',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'P250',
         skin: 'Facility Draft',
         rarity: 'grey',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'UMP-45',
         skin: 'Facility Dark',
         rarity: 'grey',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'Nova',
         skin: 'Mandrel',
         rarity: 'grey',
         min_float: 0,
         max_float: 0.5,
      }

   ],
   GloveCase: [
      {
         name: 'M4A4',
         skin: 'Buzz Kill',
         rarity: 'red',
         min_float: 0,
         max_float: 0.7,
      },
      {
         name: 'SSG 08',
         skin: 'Dragonfir',
         rarity: 'red',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'FAMAS',
         skin: 'Mecha Industries',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'P90',
         skin: 'Shallow Grave',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.75,
      },
      {
         name: 'Sawed-Off',
         skin: 'Wasteland Princess',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.7,
      },
      {
         name: 'USP-S',
         skin: 'Cyrex',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.55,
      },
      {
         name: 'M4A1-S',
         skin: 'Flashback',
         rarity: 'purple',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'Dual Berettas',
         skin: 'Royal Consorts',
         rarity: 'purple',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'Nova',
         skin: 'Gila',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.3,
      },
      {
         name: 'G3SG1',
         skin: 'Stinger',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.7,
      },
      {
         name: 'Glock-18',
         skin: 'Ironwork',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'MP7',
         skin: 'Cirrus',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.75,
      },
      {
         name: 'Galil AR',
         skin: 'Black Sand',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'P2000',
         skin: 'Turf',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'MP9',
         skin: 'Sand Scale',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.45,
      },
      {
         name: 'MAG-7',
         skin: 'Sonar',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.45,
      },
      {
         name: 'CZ75-Auto',
         skin: 'Polymer',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.5,
      }
   ],
   Havoc: [
      {
         name: 'AK-47',
         skin: 'X-Ray',
         rarity: 'red',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'AWP',
         skin: 'Silk Tiger',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.6,
      },
      {
         name: 'MAC-10',
         skin: 'Hot Snakes',
         rarity: 'pink',
         min_float: 0,
         max_float: 1,
      },
      {
         name: 'SG 553',
         skin: 'Hypnotic',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.08,
      },
      {
         name: 'Glock-18',
         skin: 'Franklin',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.4,
      },
      {
         name: 'Galil AR',
         skin: 'Phoenix Blacklight',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.7,
      },
      {
         name: 'P250',
         skin: 'Bengal Tiger',
         rarity: 'blue',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'Desert Eagle',
         skin: 'Night Heist',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.65,
      },
      {
         name: 'P90',
         skin: 'Tiger Pit',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'Negev',
         skin: 'Phoenix Stencil',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.65,
      },
      {
         name: 'R8 Revolver',
         skin: 'Phoenix Marker',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.6,
      },
      {
         name: 'Nova',
         skin: 'Rust Coat',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.8,
      },
      {
         name: 'MP7',
         skin: 'Vault Heist',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.6,
      },
      {
         name: 'UMP-45',
         skin: 'Houndstooth',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.6,
      },
      {
         name: 'M249',
         skin: 'Predator',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'Tec-9',
         skin: 'Phoenix Chalk',
         rarity: 'grey',
         min_float: 0,
         max_float: 0.8,
      },
      {
         name: 'Dual Berettas',
         skin: 'Heist',
         rarity: 'grey',
         min_float: 0,
         max_float: 0.7,
      },
      {
         name: 'Sawed-Off',
         skin: 'Clay Ambush',
         rarity: 'grey',
         min_float: 0,
         max_float: 0.6,
      },
      {
         name: 'PP-Bizon',
         skin: 'Death Rattle',
         rarity: 'grey',
         min_float: 0.08,
         max_float: 0.5,
      }
   ],
   Control: [
      {
         name: 'AWP',
         skin: 'Fade',
         rarity: 'red',
         min_float: 0,
         max_float: 0.08,
      },
      {
         name: 'M4A1-S',
         skin: 'Blue Phosphor',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.08,
      },
      {
         name: 'USP-S',
         skin: 'Target Acquired',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.5,
      },
      {
         name: 'Five-SeveN',
         skin: 'Berries And Cherries',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.1,
      },
      {
         name: 'UMP-45',
         skin: 'Crime Scene',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.75,
      },
      {
         name: 'FAMAS',
         skin: 'Prime Conspiracy',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.55,
      },
      {
         name: 'M4A4',
         skin: 'Global Offensive',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.7,
      },
      {
         name: 'P2000',
         skin: 'Dispatch',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.65,
      },
      {
         name: 'SSG 08',
         skin: 'Threat Detected',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.65,
      },
      {
         name: 'SCAR-20',
         skin: 'Magna Carta',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.6,
      },
      {
         name: 'MP5-SD',
         skin: 'Nitro',
         rarity: 'light_blue',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'Desert Eagle',
         skin: 'The Bronze',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.3,
      },
      {
         name: 'MAG-7',
         skin: 'Carbon Fiber',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.12,
      },
      {
         name: 'Dual Berettas',
         skin: 'Switch Board',
         rarity: 'light_blue',
         min_float: 0,
         max_float: 0.65,
      },
      {
         name: 'P250',
         skin: 'Forest Night',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'CZ75-Auto',
         skin: 'Jungle Dashed',
         rarity: 'grey',
         min_float: 0.06,
         max_float: 0.8,
      },
      {
         name: 'MP9',
         skin: 'Army Sheen',
         rarity: 'grey',
         min_float: 0,
         max_float: 0.3,
      },
      {
         name: 'XM1014',
         skin: 'Charter',
         rarity: 'grey',
         min_float: 0,
         max_float: 0.65,
      },
      {
         name: 'AUG',
         skin: 'Surveillance',
         rarity: 'grey',
         min_float: 0,
         max_float: 0.6,
      }
   ],

};