module.exports = {

   ChromaCase: [
      {
         name: 'Galil AR',
         skin: 'Chatterbox',
         rarity: 'red',
         min_float: 0.35,
         max_float: 0.85,
         isInStattrak: true,
      },
      {
         name: 'AWP',
         skin: "Man-o'-war",
         rarity: 'red',
         min_float: 0.1,
         max_float: 0.2,
         isInStattrak: true,
      },
      {
         name: 'M4A4',
         skin: '龍王 (Dragon King)',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.75,
         isInStattrak: true,
      },
      {
         name: 'AK-47',
         skin: 'Cartel',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.75,
         isInStattrak: true,
      },
      {
         name: 'P250',
         skin: 'Muertos',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.6,
         isInStattrak: true,
      },
      {
         name: 'Desert Eagle',
         skin: 'Naga',
         rarity: 'purple',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'Sawed-Off',
         skin: 'Serenity',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.5,
         isInStattrak: true,
      },
      {
         name: 'MAC-10',
         skin: 'Malachite',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.5,
         isInStattrak: true,
      },
      {
         name: 'Dual Berettas',
         skin: 'Urban Shock',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.47,
         isInStattrak: true,
      },
      {
         name: 'MP9',
         skin: 'Deadly Poison',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'Glock-18',
         skin: 'Catacombs',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.5,
         isInStattrak: true,
      },
      {
         name: 'M249',
         skin: 'System Lock',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.8,
         isInStattrak: true,
      },
      {
         name: 'SCAR-20',
         skin: 'Grotto',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.5,
         isInStattrak: true,
      },
      {
         name: 'XM1014',
         skin: 'Quicksilver',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.5,
         isInStattrak: true,
      },
   ],
   Chroma2Case: [
      {
         name: 'M4A1-S',
         skin: 'Hyper Beast',
         rarity: 'red',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'MAC-10',
         skin: 'Neon Rider',
         rarity: 'red',
         min_float: 0,
         max_float: 0.45,
         isInStattrak: true,
      },
      {
         name: 'Galil AR',
         skin: 'Eco',
         rarity: 'pink',
         min_float: 0.1,
         max_float: 0.85,
         isInStattrak: true,
      },
      {
         name: 'Five-SeveN',
         skin: 'Monkey Business',
         rarity: 'pink',
         min_float: 0.1,
         max_float: 0.9,
         isInStattrak: true,
      },
      {
         name: 'FAMAS',
         skin: 'Djinn',
         rarity: 'pink',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'AWP',
         skin: 'Worm God',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.45,
         isInStattrak: true,
      },
      {
         name: 'MAG-7',
         skin: 'Heat',
         rarity: 'purple',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'CZ75-Auto',
         skin: 'Pole Position',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.7,
         isInStattrak: true,
      },
      {
         name: 'UMP-45',
         skin: 'Grand Prix',
         rarity: 'purple',
         min_float: 0.25,
         max_float: 0.35,
         isInStattrak: true,
      },
      {
         name: 'AK-47',
         skin: 'Elite Build',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'Desert Eagle',
         skin: 'Bronze Deco',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.46,
         isInStattrak: true,
      },
      {
         name: 'P250',
         skin: 'Valence',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.8,
         isInStattrak: true,
      },
      {
         name: 'Sawed-Off',
         skin: 'Origami',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.55,
         isInStattrak: true,
      },
      {
         name: 'Negev',
         skin: "Man-o'-war",
         rarity: 'blue',
         min_float: 0.1,
         max_float: 0.2,
         isInStattrak: true,
      },
      {
         name: 'MP7',
         skin: 'Armor Core',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.5,
         isInStattrak: true,
      },
   ],
   Chroma3Case: [
      {
         name: 'M4A1-S',
         skin: "Chantico's Fire",
         rarity: 'red',
         min_float: 0,
         max_float: 0.99,
         isInStattrak: true,
      },
      {
         name: 'PP-Bizon',
         skin: 'Judgement of Anubis',
         rarity: 'red',
         min_float: 0,
         max_float: 0.5,
         isInStattrak: true,
      },
      {
         name: 'P250',
         skin: 'Asiimov',
         rarity: 'pink',
         min_float: 0.1,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'AUG',
         skin: 'Fleet Flock',
         rarity: 'pink',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'UMP-45',
         skin: 'Primal Saber',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.77,
         isInStattrak: true,
      },
      {
         name: 'SSG 08',
         skin: 'Ghost Crusader',
         rarity: 'purple',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'XM1014',
         skin: 'Black Tie',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.75,
         isInStattrak: true,
      },
      {
         name: 'Galil AR',
         skin: 'Firefight',
         rarity: 'purple',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'Tec-9',
         skin: 'Re-Entry',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.43,
         isInStattrak: true,
      },
      {
         name: 'CZ75-Auto',
         skin: 'Red Astor',
         rarity: 'purple',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'MP9',
         skin: 'Bioleak',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.5,
         isInStattrak: true,
      },
      {
         name: 'SG 553',
         skin: 'Atlas',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.81,
         isInStattrak: true,
      },
      {
         name: 'Dual Berettas',
         skin: 'Ventilators',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.45,
         isInStattrak: true,
      },
      {
         name: 'M249',
         skin: 'Spectre',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.5,
         isInStattrak: true,
      },
      {
         name: 'Sawed-Off',
         skin: 'Fubar',
         rarity: 'blue',
         min_float: 0.4,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'P2000',
         skin: 'Oceanic',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.6,
         isInStattrak: true,
      },
      {
         name: 'G3SG1',
         skin: 'Orange Crash',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.52,
         isInStattrak: true,
      },
   ],
   ClutchCase: [
      {
         name: 'M4A4',
         skin: 'Neo-Noir',
         rarity: 'red',
         min_float: 0,
         max_float: 0.9,
         isInStattrak: true,
      },
      {
         name: 'MP7',
         skin: 'Bloodsport',
         rarity: 'red',
         min_float: 0,
         max_float: 0.65,
         isInStattrak: true,
      },
      {
         name: 'USP-S',
         skin: 'Cortex',
         rarity: 'pink',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'AWP',
         skin: 'Mortis',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.64,
         isInStattrak: true,
      },
      {
         name: 'AUG',
         skin: 'Stymphalian',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.63,
         isInStattrak: true,
      },
      {
         name: 'Glock-18',
         skin: 'Moonrise',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.65,
         isInStattrak: true,
      },
      {
         name: 'MAG-7',
         skin: 'SWAG-7',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.92,
         isInStattrak: true,
      },
      {
         name: 'UMP-45',
         skin: 'Arctic Wolf',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.8,
         isInStattrak: true,
      },
      {
         name: 'Nova',
         skin: 'Wild Six',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.8,
         isInStattrak: true,
      },
      {
         name: 'Negev',
         skin: 'Lionfish',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.55,
         isInStattrak: true,
      },
      {
         name: 'R8 Revolver',
         skin: 'Grip',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'MP9',
         skin: 'Black Sand',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'SG 553',
         skin: 'Aloha',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.55,
         isInStattrak: true,
      },
      {
         name: 'P2000',
         skin: 'Urban Hazard',
         rarity: 'blue',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'PP-Bizon',
         skin: 'Night Riot',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.8,
         isInStattrak: true,
      },
      {
         name: 'Five-SeveN',
         skin: 'Flame Test',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.65,
         isInStattrak: true,
      },
      {
         name: 'XM1014',
         skin: 'Oxide Blaze',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.7,
         isInStattrak: true,
      },
   ],
   CSGOWeaponCase: [
      {
         name: 'AWP',
         skin: 'Lightning Strike',
         rarity: 'red',
         min_float: 0,
         max_float: 0.08,
         isInStattrak: true,
      },
      {
         name: 'AK-47',
         skin: 'Case Hardened',
         rarity: 'pink',
         min_float: 0,
         max_float: 1,
         isInStattrak: true,
      },
      {
         name: 'Desert Eagle',
         skin: 'Hypnotic',
         rarity: 'pink',
         min_float: 0,
         max_float: 0.08,
         isInStattrak: true,
      },
      {
         name: 'Glock-18',
         skin: 'Dragon Tattoo',
         rarity: 'purple',
         min_float: 0,
         max_float: 0.08,
         isInStattrak: true,
      },
      {
         name: 'USP-S',
         skin: 'Dark Water',
         rarity: 'purple',
         min_float: 0.1,
         max_float: 0.26,
         isInStattrak: true,
      },
      {
         name: 'M4A1-S',
         skin: 'Dark Water',
         rarity: 'purple',
         min_float: 0.1,
         max_float: 0.26,
         isInStattrak: true,
      },
      {
         name: 'SG 553',
         skin: 'Ultraviolet',
         rarity: 'blue',
         min_float: 0.06,
         max_float: 0.8,
         isInStattrak: true,
      },
      {
         name: 'AUG',
         skin: 'Wings',
         rarity: 'blue',
         min_float: 0,
         max_float: 0.14,
         isInStattrak: true,
      },
      {
         name: 'MP7',
         skin: 'Skulls',
         rarity: 'blue',
         min_float: 0.1,
         max_float: 0.26,
         isInStattrak: true,
      },
   ],
};